"""Auto-generated by Detective — warrant-classed tests for src/peitho/digest.py::_loss.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.digest import _loss


@pytest.mark.detective
def test__loss_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _loss(
        r={
            "item": {"article": "A", "color": "BLACK"},
            "category": {},
            "supplier": None,
            "movement": {"below_cost": True, "below_cost_by": 100, "sold_window": 2},
        }
    )
    assert result == 200
