# detective-content-sha256: c6eaaebe96d2a4b7a2e73981569452e5fb148c307f8887f9b1ac58a883c9634b
"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::reorder_priority.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import reorder_priority


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((5, 0.2), 1.0),
        ((1, 0.5), 0.5),
    ],
)
def test_reorder_priority_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert reorder_priority(*args) == expected


@pytest.mark.detective
def test_reorder_priority_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reorder_priority(unmet_units=6, momentum=0.2)
    assert result == 1.2
