# detective-content-sha256: de5e2efba52b30704c1d655b792f71130818d488afb8c937482f06e76954726b
"""Auto-generated by Detective — warrant-classed tests for src/peitho/sku.py::_fname.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.sku import _fname


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("http://cdn/x/a.jpg",), "a.jpg"),
        (("http://cdn/x/",), "x"),
        (("a.jpg",), "a.jpg"),
    ],
)
def test__fname_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _fname(*args) == expected
