"""Auto-generated by Detective — warrant-classed tests for src/peitho/text.py::canon_map.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.text import canon_map


@pytest.mark.detective
def test_canon_map_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = canon_map({"SANDAL": 69, "SANDALS": 942})
    assert result == {"SANDAL": "SANDALS", "SANDALS": "SANDALS"}
