"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::name_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import name_class


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), "REAL"),
        ((".",), "PLACEHOLDER"),
        (("R",), "SINGLE_CHAR"),
        (("",), "EMPTY"),
    ],
)
def test_name_class_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert name_class(*args) == expected
