"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/rules.py::stagnant_action.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.rules import stagnant_action


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("IDLE_STOCK", False, False, False), "PULL_TRIAGE"),
        (("IDLE_STOCK", True, False, False), "RETURN"),
        (("IDLE_STOCK", False, True, False), "HOLD"),
        (("STOCKED", False, False, False), "NONE"),
    ],
)
def test_stagnant_action_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert stagnant_action(*args) == expected
