"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::deficit_units.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import deficit_units


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2), 1),
        ((2, 1), 0),
    ],
)
def test_deficit_units_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert deficit_units(*args) == expected
