# detective-content-sha256: 46fc8bc920e4bd25e42b1950ed36b55dff4e799169eb5114d756654628b26cd9
"""Auto-generated by Detective — warrant-classed tests for src/peitho/network.py::sells_position.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.network import sells_position


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((0.0, 10.0, 0.0), -1),
        ((5.0, 10.0, 0.0), 0),
        ((20.0, 10.0, 0.0), 1),
        ((10.0, 10.0, 0.0), 0),
    ],
)
def test_sells_position_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert sells_position(*args) == expected


@pytest.mark.detective
def test_sells_position_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sells_position(node_sales=-1.0, zero=10.0, floor=0.0)
    assert result == -1
