"""Auto-generated by Detective — warrant-classed tests for src/peitho/digest.py::sale_surprises.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.digest import sale_surprises


@pytest.mark.detective
def test_sale_surprises_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sale_surprises(
        records=[
            {
                "item": {"article": "A", "color": "BLACK"},
                "category": {},
                "supplier": None,
                "movement": {"below_cost": True, "below_cost_by": 100, "sold_window": 2},
            },
            {
                "item": {"article": "B", "color": "BLACK"},
                "category": {},
                "supplier": None,
                "movement": {"below_cost": True, "below_cost_by": 50, "sold_window": 10},
            },
            {
                "item": {"article": "C", "color": "BLACK"},
                "category": {},
                "supplier": None,
                "movement": {"below_cost": False, "below_cost_by": 0, "sold_window": 0},
            },
        ],
        top=3,
        min_group=15,
        min_deviation=1.0,
    )
    assert (
        repr(result)
        == "[Surprise(code='biggest_bleed', magnitude=500.0, fields={'item': 'B', 'color': 'BLACK', 'units': 10, 'under': 50, 'loss': 500})]"
    )


@pytest.mark.detective
def test_sale_surprises_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sale_surprises(
        records=[
            {
                "item": {"article": "H0", "color": "BLACK"},
                "category": {},
                "supplier": "HOT",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "H1", "color": "BLACK"},
                "category": {},
                "supplier": "HOT",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "H2", "color": "BLACK"},
                "category": {},
                "supplier": "HOT",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "H3", "color": "BLACK"},
                "category": {},
                "supplier": "HOT",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "H4", "color": "BLACK"},
                "category": {},
                "supplier": "HOT",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O0", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O1", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": True, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O2", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O3", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O4", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O5", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O6", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O7", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O8", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O9", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O10", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O11", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O12", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O13", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O14", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O15", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O16", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O17", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O18", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
            {
                "item": {"article": "O19", "color": "BLACK"},
                "category": {},
                "supplier": "OTHER",
                "movement": {"below_cost": False, "below_cost_by": 10, "sold_window": 1},
            },
        ],
        top=3,
        min_group=5,
        min_deviation=1.0,
    )
    assert (
        repr(result)
        == "[Surprise(code='biggest_bleed', magnitude=10.0, fields={'item': 'H0', 'color': 'BLACK', 'units': 1, 'under': 10, 'loss': 10}), Surprise(code='supplier_hot', magnitude=2.5714, fields={'supplier': 'HOT', 'pct': 100, 'norm': 28, 'count': 5, 'of': 5})]"
    )
