"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::urgency_score.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import urgency_score


@pytest.mark.detective
def test_urgency_score_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = urgency_score(cover=2, baseline=1)
    assert result == 0.0


@pytest.mark.detective
def test_urgency_score_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = urgency_score(cover=0.0, baseline=-1)
    assert result == 0.0


@pytest.mark.detective
def test_urgency_score_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = urgency_score(cover=1.0, baseline=1.0625)
    assert result == 0.0588


@pytest.mark.detective
def test_urgency_score_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = urgency_score(cover=-1.0, baseline=1)
    assert result == 1.0


@pytest.mark.detective
def test_urgency_score_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = urgency_score(cover=-1.0, baseline=0)
    assert result == 0.0
