# detective-content-sha256: aca7a992dc6586910b9ca79186ce965b52d607d62ccf6b64a9492fe6a8269de9
"""Auto-generated by Detective — warrant-classed tests for src/peitho/reconcile.py::move_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.reconcile import move_verdict


@pytest.mark.detective
def test_move_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = move_verdict(received=0.1, sold_after=0.05)
    assert result == "SOLD"
