"""Auto-generated by Detective — warrant-classed tests for src/peitho/stats.py::weighted_median.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.stats import weighted_median


@pytest.mark.detective
def test_weighted_median_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = weighted_median(pairs=[(1430, 10), (1400, 5)])
    assert result == 1430
