"""Auto-generated by Detective — warrant-classed tests for src/peitho/morning.py::is_loud.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.morning import is_loud


@pytest.mark.detective
def test_is_loud_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_loud(magnitude=500.0, threshold=200.0)
    assert result is True


@pytest.mark.detective
def test_is_loud_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_loud(magnitude=200.0, threshold=200.0)
    assert result is True


@pytest.mark.detective
def test_is_loud_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_loud(magnitude=100.0, threshold=200.0)
    assert result is False
