"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/price.py::margin_pct.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.price import margin_pct


@pytest.mark.detective
def test_margin_pct_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = margin_pct(profit=2, nrv=1)
    assert result == 200.0


@pytest.mark.detective
def test_margin_pct_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(profit=-1.0, nrv=-1)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(profit=-1.0, nrv=1.0625)
    assert result == -94.12


@pytest.mark.detective
def test_margin_pct_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(profit=-1.0, nrv=0)
    assert result is None
