"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/regime.py::article_fy_counts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.regime import article_fy_counts


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"fy1": ["A", "B"], "fy2": ["A"]}, {}), {"A": 2, "B": 1}),
        (({"fy1": ["A"], "fy2": ["B"]}, {"A": "h1", "B": "h1"}), {"A": 2, "B": 2}),
    ],
)
def test_article_fy_counts_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert article_fy_counts(*args) == expected
