# detective-content-sha256: bb58d7e54c239afb3b58f2fbf08c877eca2e5a074bb86c50e6842ad36c911ea6
"""Auto-generated by Detective — warrant-classed tests for src/peitho/restock.py::restock_votes.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.restock import restock_votes


@pytest.mark.detective
def test_restock_votes_value_0():
    """VALUE survivor — distinguishing witness (original raises ValueError: zip() argument 2 is shorter than argument 1) (confidence 0.95)."""
    try:
        _result = restock_votes(sig=(1,))
    except ValueError as _exc:
        assert str(_exc) == "zip() argument 2 is shorter than argument 1"
    except BaseException as _exc:
        pytest.fail(f"expected ValueError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected ValueError, but the call returned {_result!r}")
