"""Auto-generated by Detective — warrant-classed tests for src/peitho/digest.py::sale_winners.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.digest import sale_winners


@pytest.mark.detective
def test_sale_winners_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sale_winners(
        records=[
            {"item": {"article": "SLOW", "color": "BLACK"}, "movement": {"velocity_30d": 3, "days_of_cover": 5}},
            {"item": {"article": "OVERSOLD", "color": "BLACK"}, "movement": {"velocity_30d": 20, "days_of_cover": -3}},
            {"item": {"article": "DEEP", "color": "BLACK"}, "movement": {"velocity_30d": 10, "days_of_cover": 60}},
            {"item": {"article": "WIN1", "color": "BLACK"}, "movement": {"velocity_30d": 8, "days_of_cover": 2}},
            {"item": {"article": "WIN2", "color": "BLACK"}, "movement": {"velocity_30d": 30, "days_of_cover": 0}},
        ],
        top=1,
        min_velocity=5.0,
        max_cover=21.0,
    )
    assert (
        repr(result)
        == "[Surprise(code='top_mover', magnitude=30.0, fields={'item': 'WIN2', 'color': 'BLACK', 'sold': 30, 'cover': 0})]"
    )
