# detective-content-sha256: f2c4de72ece7724f204c6334389bb8e1d7a39becb60e24f7160eed46397cd36e
"""Auto-generated by Detective — warrant-classed tests for src/peitho/mis.py::turnover.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.mis import turnover


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((10, 5), 2.0),
        ((5, 0), 5.0),
        ((10, -1), 10.0),
        ((1, 2), 0.5),
    ],
)
def test_turnover_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert turnover(*args) == expected


@pytest.mark.detective
def test_turnover_value_0():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = turnover(units_sold=5, units_held=0)
    assert result == 5.0
    assert type(result) is float


@pytest.mark.detective
def test_turnover_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = turnover(units_sold=10, units_held=6)
    assert result == 1.667
