# detective-content-sha256: 6214037be204d860ad2f5c1754317062944c990834fe6db7f60884d5d84f2709
"""Auto-generated by Detective — warrant-classed tests for src/peitho/product.py::extract_gender_age.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.product import extract_gender_age


@pytest.mark.detective
def test_extract_gender_age_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = extract_gender_age(
        section="MENS", subsection="WOMENS", gender={"MENS": "M", "WOMENS": "F"}, age={"KIDS": "kids"}
    )
    assert result == ("M", None)
