"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/supplier.py::supplier_band.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.supplier import supplier_band


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((0.5,), "STRONG_SELLER"),
        ((0.0,), "NORMAL"),
        ((-0.3,), "SLOW"),
        ((0.15,), "STRONG_SELLER"),
        ((-0.15,), "SLOW"),
        ((0.04999999999999999,), "NORMAL"),
    ],
)
def test_supplier_band_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert supplier_band(*args) == expected


@pytest.mark.detective
def test_supplier_band_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = supplier_band(dev=-0.5)
    assert result == "DEAD_STOCK"
