"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/spatial.py::rank_sources.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.spatial import rank_sources


@pytest.mark.detective
def test_rank_sources_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rank_sources(dest="abc", sources=[1], min_cost={})
    assert repr(result) == "[(1, inf)]"
