# detective-content-sha256: 4af7bbb38e4e565c9d57eeabc8a50c89bf8765d51a7a946b505b223323904676
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/render.py::group_runs.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.render import group_runs


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([],), []),
        (
            (
                [
                    {"from_store": "A", "to_store": "B", "cost_min": None},
                    {"from_store": "A", "to_store": "B", "qty": 1, "cost_min": 15.0},
                    {"from_store": "D", "to_store": "E", "qty": 5, "cost_min": 70.0},
                    {"from_store": "D", "to_store": "E", "qty": 1, "cost_min": 50.0},
                ],
            ),
            [
                {
                    "from_store": "A",
                    "to_store": "B",
                    "leg_cost": 15.0,
                    "units": 1,
                    "variants": 2,
                    "moves": [
                        {"from_store": "A", "to_store": "B", "cost_min": None},
                        {"from_store": "A", "to_store": "B", "qty": 1, "cost_min": 15.0},
                    ],
                },
                {
                    "from_store": "D",
                    "to_store": "E",
                    "leg_cost": 50.0,
                    "units": 6,
                    "variants": 2,
                    "moves": [
                        {"from_store": "D", "to_store": "E", "qty": 5, "cost_min": 70.0},
                        {"from_store": "D", "to_store": "E", "qty": 1, "cost_min": 50.0},
                    ],
                },
            ],
        ),
    ],
)
def test_group_runs_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert group_runs(*args) == expected
