"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/regime.py::classify.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.regime import classify


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"fy1": ["A", "B"], "fy2": ["A"]}, {}, 2), {"A": "BASE", "B": "SEASONAL"}),
        (({"fy1": ["A"]}, {}, 2), {"A": "UNKNOWN"}),
    ],
)
def test_classify_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert classify(*args) == expected
