"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/price.py::clearance_band.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.price import clearance_band


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1.0625,), "CLEARANCE"),
        ((1.0,), "CLEARANCE"),
        ((0.9,), "PROMO"),
        ((0.4,), "PROMO"),
        ((0.30000000000000004,), "NORMAL"),
    ],
)
def test_clearance_band_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert clearance_band(*args) == expected


@pytest.mark.detective
def test_clearance_band_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = clearance_band(dev=-1.0)
    assert result == "FULL_PRICE"


@pytest.mark.detective
def test_clearance_band_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = clearance_band(dev=0.0)
    assert result == "NORMAL"
