# detective-content-sha256: 2339b62214fe01619dd64a1117bc0dff02a94782e124201d1f6d40b16f544905
"""Auto-generated by Detective — warrant-classed tests for src/peitho/noticer.py::describe.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.noticer import describe


@pytest.mark.detective
def test_describe_value_0():
    """VALUE survivor — distinguishing witness (original raises ValueError: zip() argument 2 is shorter than argument 1) (confidence 0.95)."""
    try:
        _result = describe(sig=(1,))
    except ValueError as _exc:
        assert str(_exc) == "zip() argument 2 is shorter than argument 1"
    except BaseException as _exc:
        pytest.fail(f"expected ValueError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected ValueError, but the call returned {_result!r}")
