"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::customer_segment.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import customer_segment


@pytest.mark.detective
def test_customer_segment_value_0():
    """VALUE survivor — distinguishing witness (original raises KeyError: 'frequency') (confidence 0.95)."""
    try:
        _result = customer_segment(rfm={}, baselines={}, valuable_at=1.0, overdue_at=1.0)
    except KeyError as _exc:
        assert str(_exc) == "'frequency'"
    except BaseException as _exc:
        pytest.fail(f"expected KeyError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected KeyError, but the call returned {_result!r}")
