# detective-content-sha256: 27f87dd5b36609271e1b0be344be8d22477680421cbcf8405e9c311a18460bab
"""Auto-generated by Detective — warrant-classed tests for src/peitho/cassette.py::cassette_source.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.cassette import cassette_source


@pytest.mark.detective
def test_cassette_source_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cassette_source(env_value="abc")
    assert result == "ENV"


@pytest.mark.detective
def test_cassette_source_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = cassette_source(env_value="")
    assert result == "DEFAULT"
