# detective-content-sha256: 1c0e00fd9fc5ed8e51836a6501de803211e7e3a81e2d1c313ad988c4dc33d52d
"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::coverage_target.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import coverage_target


@pytest.mark.detective
def test_coverage_target_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = coverage_target(velocity=1.0625, target_cover_days=1.0625, selling=True)
    assert result == 1


@pytest.mark.detective
def test_coverage_target_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = coverage_target(velocity=0.0, target_cover_days=0.0, selling=True)
    assert result == 1
