# detective-content-sha256: b6698ed36b3b93b63df4b36072634ba3496128d99444eb1c14a86276a2dfacff
"""Auto-generated by Detective — warrant-classed tests for src/peitho/position.py::hamming.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.position import hamming


@pytest.mark.detective
def test_hamming_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = hamming(sig_a=(1,), sig_b=(1,))
    assert result == 0
