"""Auto-generated by Detective — warrant-classed tests for src/peitho/sku.py::cluster_by_hash.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.sku import cluster_by_hash


@pytest.mark.detective
def test_cluster_by_hash_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cluster_by_hash(item_hashes={"a": "h1", "b": "h1", "c": "h2"})
    assert result == [["a", "b"]]
