"""Auto-generated by Detective — warrant-classed tests for src/peitho/sku.py::age_years.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.sku import age_years


@pytest.mark.detective
def test_age_years_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = age_years(fy=23, current_fy=26)
    assert result == 3


@pytest.mark.detective
def test_age_years_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = age_years(fy=None, current_fy=26)
    assert result is None
