"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/supply.py::reorder_qty.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.supply import reorder_qty


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((10, 20), 10),
        ((20, 10), 0),
    ],
)
def test_reorder_qty_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert reorder_qty(*args) == expected
