"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/supply.py::base_stock_level.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.supply import base_stock_level


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((4.0, 30, 30, 0), 240),
        ((0.0, 30, 30, 5), 5),
        ((1.0625, 1.0625, 1.0625, 1), 3),
    ],
)
def test_base_stock_level_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert base_stock_level(*args) == expected
