"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::urgency_band.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import urgency_band


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1.0625,), "CRITICAL"),
        ((0.8,), "CRITICAL"),
        ((0.7000000000000001,), "HIGH"),
        ((0.6,), "HIGH"),
        ((0.5,), "WATCH"),
        ((0.4,), "WATCH"),
        ((0.30000000000000004,), "OK"),
    ],
)
def test_urgency_band_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert urgency_band(*args) == expected
