"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::allocate.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import allocate


@pytest.mark.detective
def test_allocate_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = allocate(need=2, sources=[("N3", 0, 55.0), ("WH", 3, 0.0)])
    assert result == ([("WH", 2)], 0)


@pytest.mark.detective
def test_allocate_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = allocate(need=4, sources=[("WH", 3, 0.0), ("N4", 10, 180.0)])
    assert result == ([("WH", 3), ("N4", 1)], 0)
