# detective-content-sha256: de62abf0c82c56dff81f931a931546f2a6da20054254e61a428ba93838760d1b
"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::supplier_worth_ordering.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import supplier_worth_ordering


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((3, 3), "SUPPLIER_ORDER"),
        ((2, 3), "SUPPLIER_HOLD"),
        ((5, 3), "SUPPLIER_ORDER"),
    ],
)
def test_supplier_worth_ordering_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert supplier_worth_ordering(*args) == expected
