"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/supply.py::critical_fractile.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.supply import critical_fractile


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((9.0, 1.0), 0.9),
        ((0.0, 0.0), 0.0),
    ],
)
def test_critical_fractile_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert critical_fractile(*args) == expected


@pytest.mark.detective
def test_critical_fractile_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = critical_fractile(underage_cost=-1.0, overage_cost=0.0)
    assert result == 0.0


@pytest.mark.detective
def test_critical_fractile_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = critical_fractile(underage_cost=1.0, overage_cost=0.0)
    assert result == 1.0
