"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/season.py::age_cohort.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.season import age_cohort


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), "CURRENT"),
        ((180,), "LATE_SEASON"),
        ((365,), "CARRYOVER"),
        ((730,), "AGED"),
        ((None,), "UNKNOWN"),
    ],
)
def test_age_cohort_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert age_cohort(*args) == expected
