"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::classify_cell.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import classify_cell


@pytest.mark.detective
def test_classify_cell_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_cell(stock=1, recent_sales=2, total_sales=3, role="abc")
    assert result == "STOCKED"


@pytest.mark.detective
def test_classify_cell_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=0, recent_sales=0, total_sales=0, role="")
    assert result == "EMPTY"


@pytest.mark.detective
def test_classify_cell_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=-1, recent_sales=-1, total_sales=-1, role="RETAIL")
    assert result == "EMPTY"


@pytest.mark.detective
def test_classify_cell_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=0, recent_sales=1, total_sales=2, role="RETAIL")
    assert result == "LIVE_SHORTAGE"


@pytest.mark.detective
def test_classify_cell_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=-1, recent_sales=1, total_sales=3, role="a")
    assert result == "STALE_OUT"


@pytest.mark.detective
def test_classify_cell_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=-1, recent_sales=0, total_sales=1, role="abc")
    assert result == "STALE_OUT"


@pytest.mark.detective
def test_classify_cell_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=1, recent_sales=3, total_sales=0, role="RETAIL")
    assert result == "IDLE_STOCK"


@pytest.mark.detective
def test_classify_cell_value_7():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=2, recent_sales=3, total_sales=-1, role="a")
    assert result == "IDLE_STOCK"


@pytest.mark.detective
def test_classify_cell_value_8():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_cell(stock=1, recent_sales=1, total_sales=1, role="x")
    assert result == "STOCKED"
