# detective-content-sha256: 062cf945876913610a2dcb7e765d790ed0a0d8d197b069e3cd1573dee9e81885
"""Auto-generated by Detective — warrant-classed tests for src/peitho/source.py::parse_report_table.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.source import parse_report_table


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([], "item_code", "supplier"), {}),
        (([["total_mode", "item_code"]], "item_code", "supplier"), {}),
        (
            ([["total_mode", "item_code", "supplier"], [0, "A1", "ACME"]], "item_code", "supplier"),
            {"A1": "ACME"},
        ),
        (
            (
                [
                    ["total_mode", "item_code", "supplier"],
                    [0, "A1", "ACME"],
                    [0, "A1", "DUP"],
                    [1, "S", "X"],
                    [0, "  ", "Y"],
                    [0, "A2", ""],
                    [0, "A3", "  "],
                ],
                "item_code",
                "supplier",
            ),
            {"A1": "ACME"},
        ),
    ],
)
def test_parse_report_table_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert parse_report_table(*args) == expected
