# detective-content-sha256: c1ef29bf5338b40b40ffbcb11c981b5215907756baa0f8b4bc4f569780195e41
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/render.py::humanize_reason.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.render import humanize_reason


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("",), ""),
        (("INVENTORY:deficit SPATIAL:short",), "low cover, below target"),
    ],
)
def test_humanize_reason_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert humanize_reason(*args) == expected
