# detective-content-sha256: d8e865dc87812fdf2f6c7911b14c2dbc8f7b7d822d8b9842cf554c4511f69f01
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/style.py::prettify_category.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.style import prettify_category


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"sub_category": "Sneakers", "age_group": "kids"},), "Kids' Sneakers"),
        (({"gender": "M"},), "Men's"),
    ],
)
def test_prettify_category_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert prettify_category(*args) == expected
