"""Auto-generated by Detective — warrant-classed tests for src/peitho/geometry.py::deviation.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.geometry import deviation


@pytest.mark.detective
def test_deviation_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = deviation(value=10, baseline=-1)
    assert result == 0.0


@pytest.mark.detective
def test_deviation_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = deviation(value=11, baseline=6)
    assert result == 0.8333


@pytest.mark.detective
def test_deviation_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = deviation(value=2, baseline=1)
    assert result == 1.0
