"""Auto-generated by Detective — warrant-classed tests for src/peitho/text.py::levenshtein.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.text import levenshtein


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("cat", ""), 3),
        (("", "cat"), 3),
    ],
)
def test_levenshtein_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert levenshtein(*args) == expected


@pytest.mark.detective
def test_levenshtein_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = levenshtein(a="abc", b="a")
    assert result == 2
