"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/supplier.py::sell_through.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.supplier import sell_through


@pytest.mark.detective
def test_sell_through_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = sell_through(sold=5, purchased=0)
    assert result is None


@pytest.mark.detective
def test_sell_through_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = sell_through(sold=2, purchased=1)
    assert result == 2.0


@pytest.mark.detective
def test_sell_through_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sell_through(sold=5, purchased=-1)
    assert result is None


@pytest.mark.detective
def test_sell_through_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sell_through(sold=89, purchased=99)
    assert result == 0.899
