"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::_days_between.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import _days_between


@pytest.mark.detective
def test__days_between_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _days_between(d_from="2025-01-01", d_to="2026-08-15")
    assert result == 591


@pytest.mark.detective
def test__days_between_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _days_between(d_from="bad", d_to="2026-01-01")
    assert result is None
