"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::build_item_record.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import build_item_record


@pytest.mark.detective
def test_build_item_record_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = build_item_record(
        article="A1",
        color="BLK",
        style_id="http://i",
        image="WOMENS",
        category="BALLERINAS",
        style={"variety": "ROUND"},
        age_days=730,
        size_stock={"38/7": 5, "39/8": 0, "40/9": 3},
        stock_by_location={"N8": 8},
    )
    assert result == {
        "item": {"article": "A1", "color": "BLK"},
        "style_id": "http://i",
        "image": "WOMENS",
        "category": "BALLERINAS",
        "style": {"variety": "ROUND"},
        "age_days": 730,
        "sizes": {"in_stock": ["38/7", "40/9"], "by_size": {"38/7": 5, "39/8": 0, "40/9": 3}},
        "stock": {"total": 8, "by_location": {"N8": 8}},
    }
