"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::build_sku_record.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import build_sku_record


@pytest.mark.detective
def test_build_sku_record_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = build_sku_record(
        article="A2", color="", size="", image=None, category={}, style={}, age_days=None, stock_by_location={}
    )
    assert result == {
        "sku": {"article": "A2", "color": "", "size": ""},
        "image": None,
        "category": {},
        "style": {},
        "age_days": None,
        "stock": {"total": 0, "by_location": {}},
    }
