"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::target_stock.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import target_stock


@pytest.mark.detective
def test_target_stock_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = target_stock(velocity=1.0625, target_cover_days=1.0625)
    assert result == 1


@pytest.mark.detective
def test_target_stock_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = target_stock(velocity=-1.0, target_cover_days=2.5)
    assert result == -2
