# detective-content-sha256: d79caa60fa5175ff8f32b44b140994ea1791e01006324e10f4dac710bbc6726c
"""Auto-generated by Detective — warrant-classed tests for src/peitho/product.py::resolve_token.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.product import resolve_token


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("BLANK", "", "X", {}, {}, {}, ["BLANK", ""], {}), ""),
        (("NEWTOKEN", "", "Y", {}, {}, {}, ["BLANK", ""], {}), "NEWTOKEN"),
    ],
)
def test_resolve_token_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert resolve_token(*args) == expected
