"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/preclear.py::should_preclear.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.preclear import should_preclear


@pytest.mark.detective
def test_should_preclear_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_preclear(high_propensity=True, days_to_sale=5, horizon_days=14, at_sell_node=False)
    assert result is True


@pytest.mark.detective
def test_should_preclear_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_preclear(high_propensity=False, days_to_sale=5, horizon_days=14, at_sell_node=False)
    assert result is False


@pytest.mark.detective
def test_should_preclear_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_preclear(high_propensity=True, days_to_sale=20, horizon_days=14, at_sell_node=False)
    assert result is False


@pytest.mark.detective
def test_should_preclear_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_preclear(high_propensity=True, days_to_sale=-1, horizon_days=14, at_sell_node=False)
    assert result is False


@pytest.mark.detective
def test_should_preclear_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = should_preclear(high_propensity=True, days_to_sale=14, horizon_days=14, at_sell_node=False)
    assert result is True


@pytest.mark.detective
def test_should_preclear_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = should_preclear(high_propensity=True, days_to_sale=0, horizon_days=14, at_sell_node=False)
    assert result is True
