# detective-content-sha256: d1ce64fb408cc9fc1e5ffb71a09bb363c330105084a36cc838fb251628c7872b
"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::velocity_by_horizon.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import velocity_by_horizon


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ([3, 1, 0, 0, 0], 137),
            {
                30: 0.1,
                60: 0.06666666666666667,
                90: 0.044444444444444446,
                120: 0.03333333333333333,
                137: 0.029197080291970802,
            },
        ),
        (
            ([1, 2, 3, 4, 5], 137),
            {
                30: 0.03333333333333333,
                60: 0.05,
                90: 0.06666666666666667,
                120: 0.08333333333333333,
                137: 0.10948905109489052,
            },
        ),
        (
            ([7], 137),
            {
                30: 0.23333333333333334,
                60: 0.11666666666666667,
                90: 0.07777777777777778,
                120: 0.058333333333333334,
                137: 0.051094890510948905,
            },
        ),
        (
            ([1, 1, 1, 1, 1], 0),
            {
                30: 0.03333333333333333,
                60: 0.03333333333333333,
                90: 0.03333333333333333,
                120: 0.03333333333333333,
                0: 0.0,
            },
        ),
    ],
)
def test_velocity_by_horizon_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert velocity_by_horizon(*args) == expected


@pytest.mark.detective
def test_velocity_by_horizon_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = velocity_by_horizon(sls_age=[1, 1, 1, 1, 1], window_days=1)
    assert result == {
        30: 0.03333333333333333,
        60: 0.03333333333333333,
        90: 0.03333333333333333,
        120: 0.03333333333333333,
        1: 5.0,
    }


@pytest.mark.detective
def test_velocity_by_horizon_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = velocity_by_horizon(sls_age=[1, 1, 1, 1, 1], window_days=-1)
    assert result == {
        30: 0.03333333333333333,
        60: 0.03333333333333333,
        90: 0.03333333333333333,
        120: 0.03333333333333333,
        -1: 0.0,
    }
