"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::canonical_articles.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import canonical_articles


@pytest.mark.detective
def test_canonical_articles_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = canonical_articles(clusters=[["NS-721", "NS-721L", "NS-721M"], ["BL-A", "BL-B"]])
    assert result == {"NS-721": "NS-721", "NS-721L": "NS-721", "NS-721M": "NS-721", "BL-A": "BL-A", "BL-B": "BL-A"}
