"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/season.py::cohort_consistency.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.season import cohort_consistency


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([],), 1.0),
        (([50.0, 50.0],), 1.0),
        (([10.0, 90.0],), 0.19999999999999996),
        (([0.0, 0.0],), 0.0),
        (([-5.0, -5.0],), 0.0),
        (([None, 50.0, 50.0],), 1.0),
    ],
)
def test_cohort_consistency_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert cohort_consistency(*args) == expected
