"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::article_style_ids.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import article_style_ids


@pytest.mark.detective
def test_article_style_ids_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = article_style_ids(hashes={"A": "3f9a1c2d55", "B": "3f9a1c2d55"})
    assert result == {"A": "img:3f9a1c2d", "B": "img:3f9a1c2d"}
