# detective-content-sha256: f89a0a1fe9f0555842891c6c7c2f2dd84d95f4d87c1ee9f8f38e71485a83f1d4
"""Auto-generated by Detective — warrant-classed tests for src/peitho/reconcile.py::flow_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.reconcile import flow_class


@pytest.mark.detective
def test_flow_class_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = flow_class(variant_net_total=1)
    assert result == "SUPPLIER_IN"
