"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::build_wide_item_record.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import build_wide_item_record


@pytest.mark.detective
def test_build_wide_item_record_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = build_wide_item_record(
        article="A1",
        color="BLK",
        style_id="img:x",
        image="http://i",
        category={"cluster": "Closed Footwear", "sub_category": "Shoes"},
        style={"variety": "DERBY"},
        age_days=730,
        size_stock={"40": 5, "41": 0},
        stock_by_location={"N8": 5},
        movement={"velocity_30d": 3},
    )
    assert result == {
        "item": {"article": "A1", "color": "BLK"},
        "style_id": "img:x",
        "image": "http://i",
        "category": {"cluster": "Closed Footwear", "sub_category": "Shoes"},
        "style": {"variety": "DERBY"},
        "age_days": 730,
        "sizes": {"in_stock": ["40"], "by_size": {"40": 5, "41": 0}},
        "stock": {"total": 5, "by_location": {"N8": 5}},
        "movement": {"velocity_30d": 3},
    }
