# detective-content-sha256: 2acadb5f226073bc8194e95c4b870e6625c6e9edaece443cbd436905799cea4f
"""Auto-generated by Detective — warrant-classed tests for src/peitho/cassette.py::manifest_value.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.cassette import manifest_value


@pytest.mark.detective
def test_manifest_value_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = manifest_value(manifest={}, key="abc", defaults={})
    assert result == "abc"
