"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/preclear.py::high_sale_propensity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.preclear import high_sale_propensity


@pytest.mark.detective
def test_high_sale_propensity_swap_0():
    """SWAP survivor [SWAP_0c6503f9] — velocity_per_day != baseline_per_day; non-commutative (confidence 0.6)."""
    result_ab = high_sale_propensity(1, 2)
    result_ba = high_sale_propensity(2, 1)
    assert result_ab != result_ba, "SWAP: parameter order should matter"


@pytest.mark.detective
def test_high_sale_propensity_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = high_sale_propensity(velocity_per_day=4.0, baseline_per_day=4.0, min_deviation=0.0)
    assert result is True


@pytest.mark.detective
def test_high_sale_propensity_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = high_sale_propensity(1, 2)
    assert result is False


@pytest.mark.detective
def test_high_sale_propensity_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = high_sale_propensity(2, 1)
    assert result is True
