"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/price.py::dump_age_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.price import dump_age_class


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("CLEARANCE", 400, 365), "AGED_CLEARANCE"),
        (("CLEARANCE", 100, 365), "FRESH_DUMP"),
        (("NORMAL", 400, 365), "NOT_DUMPED"),
        (("CLEARANCE", None, 365), "AGE_UNKNOWN"),
        (("PROMO", 500, 365), "AGED_CLEARANCE"),
    ],
)
def test_dump_age_class_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert dump_age_class(*args) == expected


@pytest.mark.detective
def test_dump_age_class_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = dump_age_class(band="CLEARANCE", age_days=-1, aged_threshold_days=-1)
    assert result == "AGED_CLEARANCE"
