"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::cover_days.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import cover_days


@pytest.mark.detective
def test_cover_days_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cover_days(stock=1, sale_qty=2, window_days=3)
    assert result == 1.5


@pytest.mark.detective
def test_cover_days_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = cover_days(stock=2, sale_qty=-1, window_days=1)
    assert result is None


@pytest.mark.detective
def test_cover_days_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = cover_days(stock=-1, sale_qty=-1, window_days=-1)
    assert result is None
