"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/regime.py::regime.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.regime import regime


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((2, 1), "UNKNOWN"),
        ((2, 3), "BASE"),
        ((3, 3), "BASE"),
        ((1, 3), "SEASONAL"),
        ((0, 3), "UNKNOWN"),
        ((1, 2, 3), "SEASONAL"),
    ],
)
def test_regime_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert regime(*args) == expected
