"""Auto-generated by Detective — warrant-classed tests for src/peitho/export.py::build_movement.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.export import build_movement


@pytest.mark.detective
def test_build_movement_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = build_movement(
        velocity_30d=1, sold_window=2, stock_total=3, nrv=1.0625, cogs=1.0625, discounted_sale=1.0625
    )
    assert result == {
        "velocity_30d": 1,
        "sold_window": 2,
        "sell_through_pct": 40.0,
        "days_of_cover": 90.0,
        "sale_price": 1,
        "on_sale_pct": 100,
        "margin_pct": 0.0,
        "below_cost": False,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=2, sold_window=-1, stock_total=1, nrv=1.0625, cogs=0.0, discounted_sale=2.5)
    assert result == {
        "velocity_30d": 2,
        "sold_window": -1,
        "sell_through_pct": None,
        "days_of_cover": 15.0,
        "sale_price": None,
        "on_sale_pct": 235,
        "margin_pct": 100.0,
        "below_cost": False,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=0, sold_window=1, stock_total=0, nrv=0.0, cogs=0.0, discounted_sale=0.0)
    assert result == {
        "velocity_30d": 0,
        "sold_window": 1,
        "sell_through_pct": 100.0,
        "days_of_cover": None,
        "sale_price": None,
        "on_sale_pct": None,
        "margin_pct": None,
        "below_cost": None,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=3, sold_window=-1, stock_total=0, nrv=1, cogs=2.5, discounted_sale=1.0625)
    assert result == {
        "velocity_30d": 3,
        "sold_window": -1,
        "sell_through_pct": 100.0,
        "days_of_cover": 0.0,
        "sale_price": None,
        "on_sale_pct": 106,
        "margin_pct": -150.0,
        "below_cost": True,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=-1, sold_window=1, stock_total=3, nrv=0, cogs=2.5, discounted_sale=-1.0)
    assert result == {
        "velocity_30d": -1,
        "sold_window": 1,
        "sell_through_pct": 25.0,
        "days_of_cover": None,
        "sale_price": None,
        "on_sale_pct": None,
        "margin_pct": None,
        "below_cost": None,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(
        velocity_30d=23, sold_window=95, stock_total=154, nrv=1000.0, cogs=50.0, discounted_sale=560.0
    )
    assert result == {
        "velocity_30d": 23,
        "sold_window": 95,
        "sell_through_pct": 38.2,
        "days_of_cover": 200.9,
        "sale_price": 11,
        "on_sale_pct": 56,
        "margin_pct": 95.0,
        "below_cost": False,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=0, sold_window=2, stock_total=-1, nrv=1, cogs=1.0625, discounted_sale=0.0)
    assert result == {
        "velocity_30d": 0,
        "sold_window": 2,
        "sell_through_pct": 200.0,
        "days_of_cover": None,
        "sale_price": 0,
        "on_sale_pct": 0,
        "margin_pct": -6.2,
        "below_cost": True,
        "below_cost_by": 0,
    }


@pytest.mark.detective
def test_build_movement_value_7():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=0, sold_window=0, stock_total=0, nrv=1.0, cogs=0.0, discounted_sale=0.0)
    assert result == {
        "velocity_30d": 0,
        "sold_window": 0,
        "sell_through_pct": None,
        "days_of_cover": None,
        "sale_price": None,
        "on_sale_pct": 0,
        "margin_pct": 100.0,
        "below_cost": False,
        "below_cost_by": None,
    }


@pytest.mark.detective
def test_build_movement_value_8():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=-1, sold_window=1, stock_total=0, nrv=100.0, cogs=300.0, discounted_sale=-64.0)
    assert result == {
        "velocity_30d": -1,
        "sold_window": 1,
        "sell_through_pct": 100.0,
        "days_of_cover": None,
        "sale_price": 100,
        "on_sale_pct": -64,
        "margin_pct": -200.0,
        "below_cost": True,
        "below_cost_by": 200,
    }


@pytest.mark.detective
def test_build_movement_value_9():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = build_movement(velocity_30d=0, sold_window=0, stock_total=0, nrv=100.0, cogs=300.0, discounted_sale=-64.0)
    assert result == {
        "velocity_30d": 0,
        "sold_window": 0,
        "sell_through_pct": None,
        "days_of_cover": None,
        "sale_price": None,
        "on_sale_pct": -64,
        "margin_pct": -200.0,
        "below_cost": True,
        "below_cost_by": None,
    }
