"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::split_name.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import split_name


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), ("abc", "")),
        (("",), ("", "")),
        (("J.R. Smith",), ("J.R.", "Smith")),
        (("John Miller",), ("John", "Miller")),
        (("John Robert Miller",), ("John", "Robert Miller")),
    ],
)
def test_split_name_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert split_name(*args) == expected
