# detective-content-sha256: 52fe9a7fb34241841a6ed82fbda2b7105a60198a4ef969ab5162c54d818ff5a5
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/style.py::bank_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.style import bank_class


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("INVENTORY",), "inv"),
        (("FOO",), ""),
    ],
)
def test_bank_class_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert bank_class(*args) == expected
