"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::decode_customer_code.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import decode_customer_code


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), (None, None)),
        (("AC0000012345",), ("AC", 12345)),
    ],
)
def test_decode_customer_code_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert decode_customer_code(*args) == expected
