"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::rank_surplus.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import rank_surplus


@pytest.mark.detective
def test_rank_surplus_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rank_surplus(
        dest="N8",
        sources=[("WH", 5, "HEAD_OFFICE"), ("N4", 1, "WAREHOUSE"), ("N3", 2, "RETAIL")],
        min_cost={("WH", "N8"): 15.0, ("N4", "N8"): 180.0, ("N3", "N8"): 55.0},
    )
    assert result == [
        ("WH", 5, "HEAD_OFFICE", 15.0),
        ("N3", 2, "RETAIL", 55.0),
        ("N4", 1, "WAREHOUSE", 180.0),
    ]


@pytest.mark.detective
def test_rank_surplus_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rank_surplus(
        dest="N5",
        sources=[("N8", 2, "RETAIL"), ("N4", 9, "WAREHOUSE")],
        min_cost={("N8", "N5"): 50.0},
    )
    assert repr(result) == "[('N8', 2, 'RETAIL', 50.0), ('N4', 9, 'WAREHOUSE', inf)]"
