# detective-content-sha256: 1729f4b67cea459603db403478a18d287d4149379160fa4387747df03681f21e
"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/significance.py::move_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.significance import move_verdict


@pytest.mark.detective
def test_move_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = move_verdict(velocity=1.0625, min_velocity=1.0625)
    assert result == "KEEP"


@pytest.mark.detective
def test_move_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = move_verdict(velocity=-1.0, min_velocity=0.0)
    assert result == "DROP_SLOW"
