"""Auto-generated by Detective — warrant-classed tests for src/peitho/sku.py::parse_sku.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.sku import parse_sku


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("26p500",), (26, 500)),
        (("XX-AB12345N",), (None, None)),
    ],
)
def test_parse_sku_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert parse_sku(*args) == expected
