# detective-content-sha256: a97791cc1058ca94d2b7f9276590ca326ae5054a3e7a7c6de12c94a27c2d2786
"""Auto-generated by Detective — warrant-classed tests for src/peitho/mis.py::margin_pct.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.mis import margin_pct


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((100.0, 60.0), 40.0),
        ((100.0, 0.0), 100.0),
        ((50, 100), -100.0),
        ((5, 0), 100.0),
        ((1.0625, 1.0625), 0.0),
        ((1, 2), -100.0),
        ((2, 1), 50.0),
    ],
)
def test_margin_pct_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert margin_pct(*args) == expected


@pytest.mark.detective
def test_margin_pct_swap_0():
    """SWAP survivor [SWAP_9ab51a1b] — revenue != cogs; non-commutative (confidence 0.6)."""
    result_ab = margin_pct(1, 2)
    result_ba = margin_pct(2, 1)
    assert result_ab != result_ba, "SWAP: parameter order should matter"


@pytest.mark.detective
def test_margin_pct_swap_1():
    """SWAP survivor [SWAP_0a9aca78] — revenue != cogs; non-commutative (confidence 0.6)."""
    result_ab = margin_pct(1, 2)
    result_ba = margin_pct(2, 1)
    assert result_ab != result_ba, "SWAP: parameter order should matter"


@pytest.mark.detective
def test_margin_pct_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = margin_pct(revenue=0.0, cogs=0.0)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = margin_pct(revenue=-5.0, cogs=10.0)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = margin_pct(revenue=-60, cogs=10)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = margin_pct(revenue=0.0, cogs=10.0)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(revenue=100.0, cogs=60.0)
    assert result == 40.0


@pytest.mark.detective
def test_margin_pct_value_7():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(revenue=-5.0, cogs=10.0)
    assert result is None


@pytest.mark.detective
def test_margin_pct_value_8():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(revenue=99.0, cogs=60.0)
    assert result == 39.4


@pytest.mark.detective
def test_margin_pct_value_9():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(revenue=1, cogs=2)
    assert result == -100.0


@pytest.mark.detective
def test_margin_pct_value_10():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = margin_pct(revenue=0.0, cogs=0.0)
    assert result is None
