"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::velocity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import velocity


@pytest.mark.detective
def test_velocity_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = velocity(sale_qty=1, window_days=2)
    assert result == 0.5


@pytest.mark.detective
def test_velocity_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = velocity(sale_qty=-1, window_days=-1)
    assert result == 0.0


@pytest.mark.detective
def test_velocity_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = velocity(sale_qty=-1, window_days=1)
    assert result == -1.0


@pytest.mark.detective
def test_velocity_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = velocity(sale_qty=-1, window_days=0)
    assert result == 0.0
