"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/season.py::is_seasonal_cohort.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.season import is_seasonal_cohort


@pytest.mark.detective
def test_is_seasonal_cohort_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(10, 4, 0.8)
    assert result is True


@pytest.mark.detective
def test_is_seasonal_cohort_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(5, 4, 0.8)
    assert result is False


@pytest.mark.detective
def test_is_seasonal_cohort_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(10, 2, 0.8)
    assert result is False


@pytest.mark.detective
def test_is_seasonal_cohort_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(10, 4, 0.3)
    assert result is False


@pytest.mark.detective
def test_is_seasonal_cohort_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(8, 3, 0.6)
    assert result is True


@pytest.mark.detective
def test_is_seasonal_cohort_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_seasonal_cohort(8, 3, 0.59)
    assert result is False
