"""Auto-generated by Detective — warrant-classed tests for src/peitho/stats.py::robust_price.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.stats import robust_price


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([(83, 3), (83, 1), (500, 1)],), (83, True)),
        (([(0, 5), (-1, 2)],), (None, False)),
    ],
)
def test_robust_price_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert robust_price(*args) == expected
