"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::bill_store.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import bill_store


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("AH-26-0128",), "AH"),
        (("",), "?"),
        (("12-345",), "?"),
        ((1,), "?"),
    ],
)
def test_bill_store_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert bill_store(*args) == expected
