"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/edges.py::admissible.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.edges import admissible


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, False, False, False, True, False, False), "TOPUP"),
        ((False, False, True, False, False, True, False), "TO_TRIAGE"),
        ((False, True, False, False, False, False, False), "TO_SELL"),
        ((False, True, True, False, False, False, False), "TO_SELL"),
        ((False, False, False, True, False, False, True), "RETURN"),
        ((False, False, False, True, False, False, False), "BLOCKED"),
    ],
)
def test_admissible_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert admissible(*args) == expected
