# detective-content-sha256: 04efeddaf260832410b4b351f2d276eb1ba2a75598447571231475bac9f44546
"""Auto-generated by Detective — warrant-classed tests for src/peitho/otp.py::interference.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.otp import interference


@pytest.mark.detective
def test_interference_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = interference(supports=0, opposes=3, support_min=2, oppose_min=2)
    assert result == "DESTRUCTIVE"


@pytest.mark.detective
def test_interference_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = interference(supports=0, opposes=1, support_min=2, oppose_min=2)
    assert result == "SILENT"


@pytest.mark.detective
def test_interference_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = interference(supports=1, opposes=0, support_min=2, oppose_min=2)
    assert result == "SILENT"
