# detective-content-sha256: 098bc764842ac31827fb525258fde0a4d14d930e6b161424786e14767632ea7a
"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/significance.py::run_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.significance import run_verdict


@pytest.mark.detective
def test_run_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = run_verdict(run_units=1, min_run_units=2)
    assert result == "DROP_THIN"


@pytest.mark.detective
def test_run_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = run_verdict(run_units=-1, min_run_units=-1)
    assert result == "KEEP"
