"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/flow.py::min_cost_flow.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.flow import min_cost_flow


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"a": 5}, {"x": 3}, {("a", "x"): 2}), {("a", "x"): 3}),
        (({"a": 2, "b": 2}, {"x": 3}, {("a", "x"): 1, ("b", "x"): 5}), {("a", "x"): 2, ("b", "x"): 1}),
        (({"a": 1}, {"x": 5}, {("a", "x"): 2}), {("a", "x"): 1}),
        (({"a": 5}, {"x": 2, "y": 2}, {("a", "x"): 1, ("a", "y"): 1}), {("a", "x"): 2, ("a", "y"): 2}),
    ],
)
def test_min_cost_flow_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert min_cost_flow(*args) == expected
