# detective-content-sha256: b5d01eb7447a6901be84b58d5bde3508e6680faffe8767e5f26595067257daae
"""Auto-generated by Detective — warrant-classed tests for src/peitho/network.py::mine_sales_zero.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.network import mine_sales_zero


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({},), 0.0),
        (({"a": 10},), 10.0),
        (({"a": 10, "b": 20},), 15.0),
        (({"a": -5, "b": 10},), 10.0),
    ],
)
def test_mine_sales_zero_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert mine_sales_zero(*args) == expected


@pytest.mark.detective
def test_mine_sales_zero_value_0():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = mine_sales_zero(sales_by_node={"a": 10})
    assert result == 10.0
    assert type(result) is float
