"""Auto-generated by Detective — warrant-classed tests for src/peitho/digest.py::_below.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.digest import _below


@pytest.mark.detective
def test__below_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _below(m={})
    assert result is False
