"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/price.py::taste_verdicts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.price import taste_verdicts


@pytest.mark.detective
def test_taste_verdicts_value_0():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'NoneType' object has no attribute 'items') (confidence 0.95)."""
    try:
        _result = taste_verdicts(grid=None, date="x", baselines={}, ages={}, min_deviation=1.0, aged_threshold_days=1)
    except AttributeError as _exc:
        assert str(_exc) == "'NoneType' object has no attribute 'items'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")
