"""Auto-generated by Detective — warrant-classed tests for src/peitho/customer.py::gender_label.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.customer import gender_label


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), "MALE_SOFT"),
        ((2,), "FEMALE"),
        ((0,), "UNSPECIFIED"),
        ((None,), "UNSPECIFIED"),
    ],
)
def test_gender_label_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert gender_label(*args) == expected
