# detective-content-sha256: 1bad179eab9172f5b3d805b258cdd40fec71ff7f1841e331f1a28a98d8b67df5
"""Auto-generated by Detective — warrant-classed tests for src/peitho/reconcile.py::leg_agreement.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.reconcile import leg_agreement


@pytest.mark.detective
def test_leg_agreement_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = leg_agreement(rec_net=1, actual_net=2)
    assert result == "MATCH"


@pytest.mark.detective
def test_leg_agreement_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = leg_agreement(rec_net=-1, actual_net=1)
    assert result == "OPPOSITE"
