"""Auto-generated by Detective — warrant-classed tests for src/peitho/query/supply.py::regime_order.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.query.supply import regime_order


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("SEASONAL", 5, 20), 0),
        (("BASE", 5, 20), 15),
    ],
)
def test_regime_order_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert regime_order(*args) == expected
