# detective-content-sha256: 511cfd21a0ab35e4fe766733246104e7136d1e7cf53089c9d0a0a39d34fff3f8
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/style.py::humanize_token.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.style import humanize_token


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("INVENTORY", "deficit"), "low cover"),
        (("FOO", "bar"), "foo bar"),
    ],
)
def test_humanize_token_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert humanize_token(*args) == expected
