# detective-content-sha256: dd8eabb1267f8a6d68b923f348ba397ff3fb8b7b55c22577162d01137095e2a4
"""Auto-generated by Detective — warrant-classed tests for src/peitho/network.py::induce_coarse_roles.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.network import induce_coarse_roles


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"WH": 0, "A": 30},), {"WH": "WAREHOUSE", "A": "RETAIL"}),
        (({},), {}),
        (({"A": 10, "B": 20},), {"A": "RETAIL", "B": "RETAIL"}),
        (({"WH": 0, "A": 30, "B": 17, "C": 5},), {"WH": "WAREHOUSE", "A": "RETAIL", "B": "RETAIL", "C": "RETAIL"}),
        (({"A": 30},), {"A": "RETAIL"}),
        (({"A": 30, "NEW": 4},), {"A": "RETAIL", "NEW": "RETAIL"}),
        (({}, 1.0625), {}),
    ],
)
def test_induce_coarse_roles_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert induce_coarse_roles(*args) == expected
