# detective-content-sha256: e5bb6f44854272ba03f370fe624d7e0c77579f2060bc2d0b6a30a55265a0ad6e
"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::recent_velocity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import recent_velocity


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([3, 1, 0, 0, 0], [0.4, 0.25, 0.2, 0.1, 0.05], 137), 0.04833333333333334),
        (([3, 1, 0, 0, 0], [0.0, 0.0, 0.0, 0.0, 0.0], 137), 0.0),
        (([3, 1, 0, 0, 0], [1.0], 137), 0.1),
    ],
)
def test_recent_velocity_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert recent_velocity(*args) == expected
