# detective-content-sha256: e629bf9446d103c0386426f320d4c15d2164f8ee421103cc8a92a56096f80abb
"""Auto-generated by Detective — warrant-classed tests for src/peitho/reconcile.py::move_outcome.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.reconcile import move_outcome


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((2, 5, 30, 20), "REALIZED_DEST"),
        ((0, 3, 30, 20), "LIVE_ELSEWHERE"),
        ((0, 0, 30, 20), "HIVOL_PENDING"),
        ((0, 0, 5, 20), "SLOW_PENDING"),
        ((0, 0, 0, 20), "NO_SIGNAL"),
        ((1, 2, 3, 4), "REALIZED_DEST"),
    ],
)
def test_move_outcome_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert move_outcome(*args) == expected


@pytest.mark.detective
def test_move_outcome_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = move_outcome(dest_sold=-1, net_sold=-1, window_vol=-1, hi_threshold=-1)
    assert result == "HIVOL_PENDING"


@pytest.mark.detective
def test_move_outcome_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = move_outcome(dest_sold=0, net_sold=1, window_vol=30, hi_threshold=20)
    assert result == "LIVE_ELSEWHERE"


@pytest.mark.detective
def test_move_outcome_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = move_outcome(dest_sold=0, net_sold=0, window_vol=1, hi_threshold=20)
    assert result == "SLOW_PENDING"
