# detective-content-sha256: 78b1b31d48739287671df6bbb02fba54558c88e6c392078dceaa09761460be5d
"""Auto-generated by Detective — warrant-classed tests for src/peitho/report/render.py::parse_reason.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.report.render import parse_reason


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("",), []),
        (
            ("INVENTORY:deficit PRICE:· SPATIAL:short VELOCITY:accelerating",),
            [("INVENTORY", "deficit"), ("SPATIAL", "short"), ("VELOCITY", "accelerating")],
        ),
    ],
)
def test_parse_reason_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert parse_reason(*args) == expected
