"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/spatial.py::edge_minutes.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.spatial import edge_minutes


@pytest.mark.detective
def test_edge_minutes_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = edge_minutes(a="abc", b="abc")
    assert result == 0.0


@pytest.mark.detective
def test_edge_minutes_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edge_minutes(a="", b="a")
    assert result == 15.0


@pytest.mark.detective
def test_edge_minutes_value_2():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = edge_minutes(a="", b="")
    assert result == 0.0
    assert type(result) is float


@pytest.mark.detective
def test_edge_minutes_value_3():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = edge_minutes(a="", b="a")
    assert result == 15.0
    assert type(result) is float
