# detective-content-sha256: 36d46e3534a94064810931c7a1ca91c046d48ac3429561788a30fc91ab5f57a8
"""Auto-generated by Detective — warrant-classed tests for src/peitho/position.py::deviation_position.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.position import deviation_position


@pytest.mark.detective
def test_deviation_position_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = deviation_position(dimension="INV", value=45.0, zero_state=30.0, tol=0.1, path=())
    assert repr(result) == "DimensionPosition(dimension='INV', sign=1, depth=0.5, zero_state=30.0, path=())"


@pytest.mark.detective
def test_deviation_position_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = deviation_position(dimension="INV", value=15.0, zero_state=30.0, tol=0.1, path=())
    assert repr(result) == "DimensionPosition(dimension='INV', sign=-1, depth=0.5, zero_state=30.0, path=())"


@pytest.mark.detective
def test_deviation_position_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = deviation_position(dimension="P", value=None, zero_state=0.2, tol=0.1, path=())
    assert repr(result) == "DimensionPosition(dimension='P', sign=0, depth=0.0, zero_state=0.2, path=())"
