# detective-content-sha256: d1f02a87b6c62b022ff47d51b0985709f7697235a6e134286950595be2c9f0e8
"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/inventory.py::band_rates.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.inventory import band_rates


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([3, 1, 0, 0, 0], 137), (0.1, 0.03333333333333333, 0.0, 0.0, 0.0)),
        (([0, 0, 0, 0, 5], 100), (0.0, 0.0, 0.0, 0.0, 0.0)),
        (
            ([1, 2, 3, 4, 5], 137),
            (0.03333333333333333, 0.06666666666666667, 0.1, 0.13333333333333333, 0.29411764705882354),
        ),
        (([7], 137), (0.23333333333333334, 0.0, 0.0, 0.0, 0.0)),
    ],
)
def test_band_rates_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert band_rates(*args) == expected
