# detective-content-sha256: a57544230531ad64f8bbd909c9c7e2acd20e2212b428b06a41897241b466a9d4
"""Auto-generated by Detective — warrant-classed tests for src/peitho/reconcile.py::gap_severity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.reconcile import gap_severity


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((0, 5), "HARD_STOCKOUT"),
        ((3, 5), "SOFT_BELOW"),
        ((3, 0), "NO_DEMAND"),
        ((1, 2), "SOFT_BELOW"),
    ],
)
def test_gap_severity_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert gap_severity(*args) == expected


@pytest.mark.detective
def test_gap_severity_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = gap_severity(dest_stock=3, dest_recent=-1)
    assert result == "NO_DEMAND"


@pytest.mark.detective
def test_gap_severity_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = gap_severity(dest_stock=-1, dest_recent=5)
    assert result == "HARD_STOCKOUT"


@pytest.mark.detective
def test_gap_severity_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = gap_severity(dest_stock=3, dest_recent=1)
    assert result == "SOFT_BELOW"
