# detective-content-sha256: d699e0f338685989c805d7770058baa4ae74356698b2cb8652a1a7b845ac749f
"""Auto-generated by Detective — warrant-classed tests for src/peitho/network.py::coarse_role.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.network import coarse_role


@pytest.mark.detective
def test_coarse_role_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = coarse_role(node_sales=0.0, zero=10.0, floor=0.0)
    assert result == "WAREHOUSE"
