# detective-content-sha256: 6934f17b815611475b8aabf3c5c758433cb4bd779642cd7baf254db4998d034d
"""Auto-generated by Detective — warrant-classed tests for src/peitho/mis.py::sell_through_pct.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.mis import sell_through_pct


@pytest.mark.detective
def test_sell_through_pct_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = sell_through_pct(units_sold=100, units_held=10)
    assert result == 90.9


@pytest.mark.detective
def test_sell_through_pct_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sell_through_pct(units_sold=-1, units_held=0)
    assert result is None


@pytest.mark.detective
def test_sell_through_pct_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = sell_through_pct(units_sold=1, units_held=0)
    assert result == 100.0
