"""Auto-generated by Detective — warrant-classed tests for src/peitho/text.py::fuzzy_fold.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.text import fuzzy_fold


@pytest.mark.detective
def test_fuzzy_fold_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = fuzzy_fold(token="Jon", corpus={"John": 2000, "Jon": 1}, max_dist=2, min_ratio=10, canon_floor=1)
    assert result == "John"
