"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/spatial.py::all_pairs_min_cost.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.spatial import all_pairs_min_cost


@pytest.mark.detective
def test_all_pairs_min_cost_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = all_pairs_min_cost(nodes=[1], edges={})
    assert result == {(1, 1): 0.0}


@pytest.mark.detective
def test_all_pairs_min_cost_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = all_pairs_min_cost(
        nodes=["A", "B", "C"], edges={("A", "B"): 1.0, ("B", "C"): 1.0, ("A", "C"): 5.0}
    )
    assert (
        repr(result)
        == "{('A', 'A'): 0.0, ('A', 'B'): 1.0, ('A', 'C'): 2.0, ('B', 'A'): inf, ('B', 'B'): 0.0, ('B', 'C'): 1.0, ('C', 'A'): inf, ('C', 'B'): inf, ('C', 'C'): 0.0}"
    )
