# detective-content-sha256: 22def275ab475d22e2df0c522fb0fe05aaeba66e66db11b9d5428c94813c500c
"""Auto-generated by Detective — warrant-classed tests for src/peitho/route.py::manufacturer_significant.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.route import manufacturer_significant


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((3, 0.02, 2, 0.05), "KEEP"),
        ((1, 0.02, 2, 0.05), "DROP_ONEOFF"),
        ((1, 0.1, 2, 0.05), "KEEP"),
        ((2, 0.0, 2, 0.05), "KEEP"),
        ((1, 1.0625, 2, 1.0625), "KEEP"),
    ],
)
def test_manufacturer_significant_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert manufacturer_significant(*args) == expected
