"""Auto-generated by Detective — warrant-classed tests for src/peitho/lenses/price.py::discount_depth.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from peitho.lenses.price import discount_depth


@pytest.mark.detective
def test_discount_depth_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = discount_depth(discount_amount=1, nrv=2)
    assert result == 33.33


@pytest.mark.detective
def test_discount_depth_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = discount_depth(discount_amount=-1.0, nrv=-1.0)
    assert result is None


@pytest.mark.detective
def test_discount_depth_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = discount_depth(discount_amount=-1.0, nrv=1.0625)
    assert result == -1600.0


@pytest.mark.detective
def test_discount_depth_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = discount_depth(discount_amount=-1.0, nrv=1.0)
    assert result is None
